### ISSUE TITLE
How to log the Recv Packets?

### ISSUE THREAD

**Issue by DWRex** [obstriker/Maple_Pshark#1]
Hi, good hack it is.
It works excellent in Sending Packets in MapleRoyals. But i still got troubles when i tried to modify it to log the recv packets.
Do you have any idea to log the Recv Packets?
Thanks!

**Comment by obstriker** [comment]
It is not clear but I left `recv` hook addresses in `MainThread` in a commented code since I did not use it or finish this feature.
You can uncomment this and modify it as you like.

The idea is to hook onto the decryption function of the game and catch any packet that was being sent before the encryption of the packet.
Then I was able to redirect the call to my function where I can do whatever I want to the packet before encryption, basically control every packet that was sent out from the client.
